### ISSUE TITLE
Arithmetic overflow error converting expression to data type int

### ISSUE THREAD

**Issue by marcelopio** [storebrand/target-mssql#10] opened 2023-02-06 11:55 UTC
I got this error trying to use this target with tap-microsoft-dataverse

```
2023-02-03T13:31:48.700704Z [info     ] 2023-02-03 10:31:48,700 Target 'target-mssql' completed reading 20 lines of input (18 records, (0 batch manifests, 1 state messages). cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:31:48.706271Z [info     ] 2023-02-03 10:31:48,706 Preparing table new_indicecorrecao cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.271696Z [info     ] 2023-02-03 10:32:01,271 Creating temp table new_indicecorrecao cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.441728Z [info     ] 2023-02-03 10:32:01,441 Inserting with SQL: INSERT INTO #new_indicecorrecao cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.441952Z [info     ] (createdonbehalfbyyominame, _modifiedonbehalfby_value, statecode, _createdonbehalfby_value, mrv_integracao_temporaria, importsequencenumber, organizationidname, modifiedbyyominame, versionnumber, utcconversiontimezonecode, createdbyyominame, modifiedbyname, new_name, _modifiedby_value, _createdby_value, timezoneruleversionnumber, new_indicecorrecaoid, new_descricao, modifiedon, modifiedonbehalfbyyominame, statuscode, createdbyname, createdon, _organizationid_value, createdonbehalfbyname, new_valormulta, modifiedonbehalfbyname, new_valorjuros, new_observao, overriddencreatedon, _ab_cdc_updated_at, _ab_cdc_deleted_at) cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.442065Z [info     ] VALUES (:createdonbehalfbyyominame, :_modifiedonbehalfby_value, :statecode, :_createdonbehalfby_value, :mrv_integracao_temporaria, :importsequencenumber, :organizationidname, :modifiedbyyominame, :versionnumber, :utcconversiontimezonecode, :createdbyyominame, :modifiedbyname, :new_name, :_modifiedby_value, :_createdby_value, :timezoneruleversionnumber, :new_indicecorrecaoid, :new_descricao, :modifiedon, :modifiedonbehalfbyyominame, :statuscode, :createdbyname, :createdon, :_organizationid_value, :createdonbehalfbyname, :new_valormulta, :modifiedonbehalfbyname, :new_valorjuros, :new_observao, :overriddencreatedon, :_ab_cdc_updated_at, :_ab_cdc_deleted_at) cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.562132Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.562487Z [info     ]   File "src/pymssql/_pymssql.pyx", line 461, in pymssql._pymssql.Cursor.execute cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.562673Z [info     ]   File "src/pymssql/_mssql.pyx", line 1087, in pymssql._mssql.MSSQLConnection.execute_query cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.562795Z [info     ]   File "src/pymssql/_mssql.pyx", line 1118, in pymssql._mssql.MSSQLConnection.execute_query cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.562897Z [info     ]   File "src/pymssql/_mssql.pyx", line 1251, in pymssql._mssql.MSSQLConnection.format_and_run_query cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.562999Z [info     ]   File "src/pymssql/_mssql.pyx", line 1789, in pymssql._mssql.check_cancel_and_raise cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.563094Z [info     ]   File "src/pymssql/_mssql.pyx", line 1835, in pymssql._mssql.raise_MSSQLDatabaseException cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.563188Z [info     ] pymssql._mssql.MSSQLDatabaseException: (8115, b'Arithmetic overflow error converting expression to data type int.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n') cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.563281Z [info     ]                                cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.563386Z [info     ] During handling of the above exception, another exception occurred: cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.563482Z [info     ]                                cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.563587Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.563718Z [info     ]   File "/home/marcelopio/repos/mrv/meltano-test/dataverse/.meltano/loaders/target-mssql/venv/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1880, in _execute_context cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.563920Z [info     ]     self.dialect.do_executemany( cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.564024Z [info     ]   File "/home/marcelopio/repos/mrv/meltano-test/dataverse/.meltano/loaders/target-mssql/venv/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 733, in do_executemany cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.564121Z [info     ]     cursor.executemany(statement, parameters) cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.564227Z [info     ]   File "src/pymssql/_pymssql.pyx", line 487, in pymssql._pymssql.Cursor.executemany cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.564321Z [info     ]   File "src/pymssql/_pymssql.pyx", line 479, in pymssql._pymssql.Cursor.execute cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
2023-02-03T13:32:01.564413Z [info     ] pymssql._pymssql.OperationalError: (8115, b'Arithmetic overflow error converting expression to data type int.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n') cmd_type=elb consumer=True name=target-mssql producer=False stdio=stderr string_id=target-mssql
```

**Comment by hholgersen** [comment] 2023-02-06 15:47
@marcelopio  Interesting. I'm not familiar with the dataverse tap, are you able to share a row or two of the stream records?

**Comment by hholgersen** [comment] 2023-02-06 15:48
And preferably also the schema statement. I tried to go through the dataverse source, but didn't find any tests that included the schema definition.

**Comment by marcelopio** [comment] 2023-02-06 17:10
I can't provide the lines for now, I will mock some and share.

As for the schema, the tap have a dynamic schema so there isn't any tests available. You can create a Dynamics 365 account in trial to test is though.

This is the schema for this table:
```
{
      "tap_stream_id": "new_indicecorrecao",
      "replication_method": "FULL_TABLE",
      "key_properties": [
        "new_indicecorrecaoid"
      ],
      "schema": {
        "properties": {
          "createdonbehalfbyyominame": {
            "type": [
              "null",
              "string"
            ]
          },
          "_modifiedonbehalfby_value": {
            "type": [
              "null",
              "string"
            ]
          },
          "statecode": {
            "type": [
              "null",
              "integer"
            ]
          },
          "_createdonbehalfby_value": {
            "type": [
              "null",
              "string"
            ]
          },
          "mrv_integracao_temporaria": {
            "type": [
              "null",
              "string"
            ]
          },
          "importsequencenumber": {
            "type": [
              "null",
              "integer"
            ]
          },
          "organizationidname": {
            "type": [
              "null",
              "string"
            ]
          },
          "modifiedbyyominame": {
            "type": [
              "null",
              "string"
            ]
          },
          "versionnumber": {
            "type": [
              "null",
              "integer"
            ]
          },
          "utcconversiontimezonecode": {
            "type": [
              "null",
              "integer"
            ]
          },
          "createdbyyominame": {
            "type": [
              "null",
              "string"
            ]
          },
          "modifiedbyname": {
            "type": [
              "null",
              "string"
            ]
          },
          "new_name": {
            "type": [
              "null",
              "string"
            ]
          },
          "_modifiedby_value": {
            "type": [
              "null",
              "string"
            ]
          },
          "_createdby_value": {
            "type": [
              "null",
              "string"
            ]
          },
          "timezoneruleversionnumber": {
            "type": [
              "null",
              "integer"
            ]
          },
          "new_indicecorrecaoid": {
            "type": [
              "null",
              "string"
            ]
          },
          "new_descricao": {
            "type": [
              "null",
              "string"
            ]
          },
          "modifiedon": {
            "format": "date-time",
            "type": [
              "null",
              "string"
            ]
          },
          "modifiedonbehalfbyyominame": {
            "type": [
              "null",
              "string"
            ]
          },
          "statuscode": {
            "type": [
              "null",
              "integer"
            ]
          },
          "createdbyname": {
            "type": [
              "null",
              "string"
            ]
          },
          "createdon": {
            "format": "date-time",
            "type": [
              "null",
              "string"
            ]
          },
          "_organizationid_value": {
            "type": [
              "null",
              "string"
            ]
          },
          "createdonbehalfbyname": {
            "type": [
              "null",
              "string"
            ]
          },
          "new_valormulta": {
            "type": [
              "null",
              "string"
            ]
          },
          "modifiedonbehalfbyname": {
            "type": [
              "null",
              "string"
            ]
          },
          "new_valorjuros": {
            "type": [
              "null",
              "string"
            ]
          },
          "new_observao": {
            "type": [
              "null",
              "string"
            ]
          },
          "overriddencreatedon": {
            "format": "date-time",
            "type": [
              "null",
              "string"
            ]
          },
          "_ab_cdc_updated_at": {
            "type": "string"
          },
          "_ab_cdc_deleted_at": {
            "type": [
              "null",
              "string"
            ]
          }
        }
      },
      "stream": "new_indicecorrecao",
      "metadata": [
        {
          "breadcrumb": [
            "properties",
            "createdonbehalfbyyominame"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "_modifiedonbehalfby_value"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "statecode"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "_createdonbehalfby_value"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "mrv_integracao_temporaria"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "importsequencenumber"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "organizationidname"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "modifiedbyyominame"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "versionnumber"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "utcconversiontimezonecode"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "createdbyyominame"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "modifiedbyname"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "new_name"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "_modifiedby_value"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "_createdby_value"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "timezoneruleversionnumber"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "new_indicecorrecaoid"
          ],
          "metadata": {
            "inclusion": "automatic",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "new_descricao"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "modifiedon"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "modifiedonbehalfbyyominame"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "statuscode"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "createdbyname"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "createdon"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "_organizationid_value"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "createdonbehalfbyname"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "new_valormulta"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "modifiedonbehalfbyname"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "new_valorjuros"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "new_observao"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "overriddencreatedon"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "_ab_cdc_updated_at"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "_ab_cdc_deleted_at"
          ],
          "metadata": {
            "inclusion": "available",
            "selected": true
          }
        },
        {
          "breadcrumb": [],
          "metadata": {
            "inclusion": "available",
            "selected": true,
            "table-key-properties": [
              "new_indicecorrecaoid"
            ]
          }
        }
      ],
      "selected": true
    },
```

**Comment by marcelopio** [comment] 2023-02-09 14:15
Tested. Still same error, I modified the code a little just to log the target schema:

```
Target schema: [Column('createdonbehalfbyyominame', VARCHAR(), table=None), Column('_modifiedonbehalfby_value', VARCHAR(), table=None), Column('statecode', BIGINT(), table=None), Column('_createdonbehalfby_value', VARCHAR(), table=None), Column('mrv_integracao_temporaria', VARCHAR(), table=None), Column('importsequencenumber', BIGINT(), table=None), Column('organizationidname', VARCHAR(), table=None), Column('modifiedbyyominame', VARCHAR(), table=None), Column('versionnumber', BIGINT(), table=None), Column('utcconversiontimezonecode', BIGINT(), table=None), Column('createdbyyominame', VARCHAR(), table=None), Column('modifiedbyname', VARCHAR(), table=None), Column('new_name', VARCHAR(), table=None), Column('_modifiedby_value', VARCHAR(), table=None), Column('_createdby_value', VARCHAR(), table=None), Column('timezoneruleversionnumber', BIGINT(), table=None), Column('new_indicecorrecaoid', VARCHAR(length=255), table=None, primary_key=True, nullable=False), Column('new_descricao', VARCHAR(), table=None), Column('modifiedon', DATETIME(), table=None), Column('modifiedonbehalfbyyominame', VARCHAR(), table=None), Column('statuscode', BIGINT(), table=None), Column('createdbyname', VARCHAR(), table=None), Column('createdon', DATETIME(), table=None), Column('_organizationid_value', VARCHAR(), table=None), Column('createdonbehalfbyname', VARCHAR(), table=None), Column('new_valormulta', VARCHAR(), table=None), Column('modifiedonbehalfbyname', VARCHAR(), table=None), Column('new_valorjuros', VARCHAR(), table=None), Column('new_observao', VARCHAR(), table=None), Column('overriddencreatedon', DATETIME(), table=None), Column('_ab_cdc_updated_at', VARCHAR(), table=None), Column('_ab_cdc_deleted_at', VARCHAR(), table=None)]
```

**Comment by hholgersen** [comment] 2023-02-09 15:12
Damn, that's a nice schema @marcelopio. Had really hoped it was the bigint problem. I will look at it, but if you are at all able to construct even an anonymized but plausible-looking record so that I can test a little, that would be really helpful. 

Ideally I would want to add this case as a unit test, if we can create a file looking similar to this: https://github.com/storebrand/target-mssql/blob/main/target_mssql/tests/data_files/simple_stream.singer.

**Comment by marcelopio** [comment] 2023-02-09 17:42
Here is a record and the schema for it. I noticed while doing it that the record is missing some columns that are present on the schema. Maybe that is the cause?

Record:
```
{"type":"RECORD","stream":"test","record":{"test1":"9994519f-9851-421f-899d-d82555741c80d","test2":"da4e5f35-d188-e547-99aa-001e86b9d664","test3":0,"test4":1,"test5":"457878bc-1d8b-e999-a817-327d3ac01117","test6":"2020-07-10T
00:00:01Z","test7":"aaabbbad-0d5b-e911-a817-111aaac01117","test8":1419999999,"test9":"AAAA","test10":"2012-01-01T00:00:00Z","test11":"BBBB","test12":null,"test13":"2019-01-30T23:59:00Z","test14":null,"test15":null,"test16":null,"
test17":null,"test18":null,"test19":null,"test20":null,"test21":null},"time_extracted":"2023-02-
09T17:25:38.199147+00:00"}
```

Schema
```
'properties': {'test22': {'type': ['null', 'string']}, 'test19': {'type': ['null', 'string']}, 'test3': {'type': ['null', 'integer']}, 'test16': {'type': ['null', 'string']}, 'test20': {'type': ['null', 'string']}, 'test15': {'type': ['null', 'integer']}, 'test23': {'type': ['null', 'string']}, 'test24': {'type': ['null', 'string']}, 'test8': {'type': ['null', 'integer']}, 'test12': {'type': ['null', 'integer']}, 'test25': {'type': ['null', 'string']}, 'test26': {'type': ['null', 'string']}, 'test9': {'type': ['null', 'string']}, 'test7': {'type': ['null', 'string']}, 'test5': {'type': ['null', 'string']}, 'test17': {'type': ['null', 'integer']}, 'test2': {'type': ['null', 'string']}, 'test11': {'type': ['null', 'string']}, 'test6': {'format': 'date-time', 'type': ['null', 'string']}, 'test27': {'type': ['null', 'string']}, 'test4': {'type': ['null', 'integer']}, 'test28': {'type': ['null', 'string']}, 'test10': {'format': 'date-time', 'type': ['null', 'string']}, 'test1': {'type': ['null', 'string']}, 'test29': {'type': ['null', 'string']}, 'test21': {'type': ['null', 'string']}, 'test30': {'type': ['null', 'string']}, 'test14': {'type': ['null', 'string']}, 'test18': {'type': ['null', 'string']}, 'test13': {'format': 'date-time', 'type': ['null', 'string']}, 'test31': {'type': 'string'}, 'test32': {'type': ['null', 'string']}}}
```

**Comment by cwegener** [comment] 2023-02-09 21:38
> Here is a record and the schema for it. I noticed while doing it that the record is missing some columns that are present on the schema. Maybe that is the cause?
> 
> Record:
> 
> ```
> {"type":"RECORD","stream":"test","record":{"test1":"9994519f-9851-421f-899d-d82555741c80d","test2":"da4e5f35-d188-e547-99aa-001e86b9d664","test3":0,"test4":1,"test5":"457878bc-1d8b-e999-a817-327d3ac01117","test6":"2020-07-10T
> 00:00:01Z","test7":"aaabbbad-0d5b-e911-a817-111aaac01117","test8":1419999999,"test9":"AAAA","test10":"2012-01-01T00:00:00Z","test11":"BBBB","test12":null,"test13":"2019-01-30T23:59:00Z","test14":null,"test15":null,"test16":null,"
> test17":null,"test18":null,"test19":null,"test20":null,"test21":null},"time_extracted":"2023-02-
> 09T17:25:38.199147+00:00"}
> ```
> 
> Schema
> 
> ```
> 'properties': {'test22': {'type': ['null', 'string']}, 'test19': {'type': ['null', 'string']}, 'test3': {'type': ['null', 'integer']}, 'test16': {'type': ['null', 'string']}, 'test20': {'type': ['null', 'string']}, 'test15': {'type': ['null', 'integer']}, 'test23': {'type': ['null', 'string']}, 'test24': {'type': ['null', 'string']}, 'test8': {'type': ['null', 'integer']}, 'test12': {'type': ['null', 'integer']}, 'test25': {'type': ['null', 'string']}, 'test26': {'type': ['null', 'string']}, 'test9': {'type': ['null', 'string']}, 'test7': {'type': ['null', 'string']}, 'test5': {'type': ['null', 'string']}, 'test17': {'type': ['null', 'integer']}, 'test2': {'type': ['null', 'string']}, 'test11': {'type': ['null', 'string']}, 'test6': {'format': 'date-time', 'type': ['null', 'string']}, 'test27': {'type': ['null', 'string']}, 'test4': {'type': ['null', 'integer']}, 'test28': {'type': ['null', 'string']}, 'test10': {'format': 'date-time', 'type': ['null', 'string']}, 'test1': {'type': ['null', 'string']}, 'test29': {'type': ['null', 'string']}, 'test21': {'type': ['null', 'string']}, 'test30': {'type': ['null', 'string']}, 'test14': {'type': ['null', 'string']}, 'test18': {'type': ['null', 'string']}, 'test13': {'format': 'date-time', 'type': ['null', 'string']}, 'test31': {'type': 'string'}, 'test32': {'type': ['null', 'string']}}}
> ```

Using this test record and the supplied schema, I cannot reproduce the error when using MS SQL Server 2022 as the target.

What is the detail of your MS SQL Server target?

**Comment by hholgersen** [comment] 2023-02-10 07:55
Just a random thought here... according to the schema (from the --discover), there is a key property `new_indicecorrecaoid`, but I don't find it in the record above. I don't see how that can amount to the arithmetic error you get, but...

Missing attributes in general shouldn't be a problem, but with missing keys I'm not entirely certain.

**Comment by hholgersen** [comment] 2023-03-02 14:42
Closing this as there has not been any further feedback and we are not able to reproduce the error. The change from INT to BIGINT (which didn't seem to help) has been merged to main now.

**Closed by hholgersen** 2023-03-02 14:42 UTC
